import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import React from "react";
import 'easymde/dist/easymde.min.css';

const workSans = localFont({
    src: [
        { path: './fonts/WorkSans-Black.ttf', weight: '900', style: 'normal' },
        { path: './fonts/WorkSans-ExtraBold.ttf', weight: '800', style: 'normal' },
        { path: './fonts/WorkSans-Bold.ttf', weight: '700', style: 'normal' },
        { path: './fonts/WorkSans-SemiBold.ttf', weight: '600', style: 'normal' },
        { path: './fonts/WorkSans-Medium.ttf', weight: '500', style: 'normal' },
        { path: './fonts/WorkSans-Regular.ttf', weight: '400', style: 'normal' },
        { path: './fonts/WorkSans-Thin.ttf', weight: '200', style: 'normal' },
        { path: './fonts/WorkSans-ExtraLight.ttf', weight: '100', style: 'normal' },
    ],
    variable: '--fon-work-sans',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fr" className={workSans.variable}>
        <head>
            {/* ✅ Google Analytics Scripts */}
            <Script
                strategy="afterInteractive"
                src="https://www.googletagmanager.com/gtag/js?id=G-FMKNGQECW9"
            />
            <Script
                id="gtag-init"
                strategy="afterInteractive"
                dangerouslySetInnerHTML={{
                    __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-XXXXXXX', {
                page_path: window.location.pathname,
              });
            `,
                }}
            />
        </head>
        <body>{children}</body>
        </html>
    );
}
