import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import React from "react";
import 'easymde/dist/easymde.min.css';
import Analytics from "./analytics";
import {GoogleAnalytics} from "@next/third-parties/google";

const workSans = localFont({
    src: [
        { path: './fonts/WorkSans-Black.ttf', weight: '900', style: 'normal' },
        { path: './fonts/WorkSans-ExtraBold.ttf', weight: '800', style: 'normal' },
        { path: './fonts/WorkSans-Bold.ttf', weight: '700', style: 'normal' },
        { path: './fonts/WorkSans-SemiBold.ttf', weight: '600', style: 'normal' },
        { path: './fonts/WorkSans-Medium.ttf', weight: '500', style: 'normal' },
        { path: './fonts/WorkSans-Regular.ttf', weight: '400', style: 'normal' },
        { path: './fonts/WorkSans-Thin.ttf', weight: '200', style: 'normal' },
        { path: './fonts/WorkSans-ExtraLight.ttf', weight: '100', style: 'normal' },
    ],
    variable: '--fon-work-sans',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fr" className={workSans.variable}>
        <body>

        {children}
        <GoogleAnalytics gaId="G-FMKNGQECW9" />
        </body>
        </html>
    );
}
